name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Tests compatibility across Ubuntu/Windows and Python/package version extremes
        os: [ubuntu-latest, windows-latest]
        dependencies: [oldest, latest]

    steps:
      - uses: actions/checkout@v6

      - name: Extract minimum Python version
        id: python-version
        shell: bash
        run: |
          MIN_PY=$(grep 'requires-python' pyproject.toml | sed -E 's/.*>=([0-9]+\.[0-9]+).*/\1/')
          echo "min=$MIN_PY" >> $GITHUB_OUTPUT

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Check if uv.lock is in sync with pyproject.toml
        if: matrix.os == 'ubuntu-latest' && matrix.dependencies == 'oldest'
        run: uv export --resolution lowest --locked

      - name: Install oldest dependencies
        if: matrix.dependencies == 'oldest'
        run: uv sync --group dev --resolution lowest --python ${{ steps.python-version.outputs.min }}

      - name: Install latest dependencies
        if: matrix.dependencies == 'latest'
        run: uv sync --group dev --resolution highest

      - name: Run ruff (check)
        run: uv run ruff check

      - name: Run ruff (format)
        run: uv run ruff format --check

      - name: Run mypy
        run: uv run mypy .

      - name: Run pytest
        run: uv run pytest
        
      - name: Upload coverage reports to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.dependencies == 'oldest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
