name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This matrix triggers 4 builds.
        # It will test 
        # - The lowest versions of the dependencies & Python defined in pyproject.toml
        # - The highest versions of the dependencies & Python defined in pyproject.toml
        # - on both Windows & Ubuntu
        # Note: Windows is slow, remove if not required
        os: [ubuntu-latest, windows-latest]
        resolution: [lowest, highest]

    steps:
      - uses: actions/checkout@v6

      - name: Extract minimum Python version
        id: python-version
        shell: bash
        run: |
          MIN_PY=$(grep 'requires-python' pyproject.toml | sed -E 's/.*>=([0-9]+\.[0-9]+).*/\1/')
          echo "min=$MIN_PY" >> $GITHUB_OUTPUT

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Check if uv.lock is in sync with pyproject.toml (only on Ubuntu & oldest Python + dependencies)
        if: matrix.os == 'ubuntu-latest' && matrix.resolution == 'lowest'
        run: uv export --resolution lowest --locked

      - name: Install packages
        run: |
          if [ "${{ matrix.resolution }}" == "lowest" ]; then
            uv sync --group dev --resolution lowest --python ${{ steps.python-version.outputs.min }}
          else
            uv sync --group dev --resolution highest
          fi

      - name: Run ruff (check)
        run: uv run ruff check

      - name: Run ruff (format)
        run: uv run ruff format --check

      - name: Run mypy
        run: uv run mypy .

      - name: Run pytest
        run: uv run pytest
        
      - name: Upload coverage reports to Codecov (only on Ubuntu & oldest Python + dependencies)
        if: matrix.os == 'ubuntu-latest' && matrix.resolution == 'lowest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
