name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]
        # python-version: ["3.10", "3.x"]
        resolution: [lowest, highest]

    steps:
      - uses: actions/checkout@v6

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          resolution-strategy: ${{ matrix.resolution }}

      - name: Install packages
        run: uv sync --group dev

      - name: Run ruff (check)
        run: uv run ruff check

      - name: Run ruff (format)
        run: uv run ruff format --check

      - name: Run mypy
        run: uv run mypy .

      - name: Run pytest
        run: uv run pytest
        
      - name: Upload coverage reports to Codecov (only on Ubuntu / Python 3.10 / oldest packages)
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10' && matrix.resolution == 'lowest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
