name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This matrix triggers 4 builds.
        # It will test 
        # - The lowest versions of the dependencies & Python version defined in pyproject.toml
        # - The latest versions of the dependencies & Python
        # - On Windows & Ubuntu
        # Note: Windows is slow, remove if not required
        os: [ubuntu-latest] #, windows-latest]
        resolution: [lowest, highest]

    steps:
      - uses: actions/checkout@v6

      - name: Extract minimum Python version
        id: python-version
        shell: bash
        run: |
          MIN_PY=$(grep 'requires-python' pyproject.toml | sed -E 's/.*>=([0-9]+\.[0-9]+).*/\1/')
          echo "min=$MIN_PY" >> $GITHUB_OUTPUT

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          python-version: ${{ matrix.resolution == 'lowest' && steps.python-version.outputs.min || '3.x' }}

      - name: Install packages
        run: uv sync --group dev --resolution ${{ matrix.resolution }}

      - name: Run ruff (check)
        run: uv run ruff check

      - name: Run ruff (format)
        run: uv run ruff format --check

      - name: Run mypy
        run: uv run mypy .

      - name: Run pytest
        run: uv run pytest
        
      - name: Upload coverage reports to Codecov (only on Ubuntu & oldest Python + dependencies)
        if: matrix.os == 'ubuntu-latest' && matrix.resolution == 'lowest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
